# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=30, unique=True)),
                ('goodsid', models.CharField(default='', max_length=10, unique=True)),
                ('goodspic', models.ImageField(upload_to='pics')),
                ('goodsprice', models.CharField(max_length=10)),
                ('isDelete', models.BooleanField(default=False)),
                ('goodsunit', models.CharField(default='500克', max_length=20)),
                ('goodsclick', models.CharField(default='', max_length=10)),
                ('gjianjie', models.CharField(default='', max_length=200)),
                ('gkucun', models.CharField(default='', max_length=10)),
                ('gcontent', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'goodsinfo',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'typeinfo',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.TypeInfo'),
        ),
    ]
