# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goodspic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
