# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180726_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goodspic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goodsunit',
            field=models.CharField(default='克', max_length=20),
        ),
    ]
