# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('rename', models.CharField(default='', max_length=32)),
                ('readdress', models.CharField(default='', max_length=124)),
                ('postcode', models.CharField(default='', max_length=20)),
                ('rephone', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'fruit_users',
            },
        ),
        migrations.CreateModel(
            name='UserTicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('out_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel')),
            ],
            options={
                'db_table': 'fruit_ticket',
            },
        ),
    ]
