# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='img',
            field=models.ImageField(null=True, upload_to='icon'),
        ),
    ]
