# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTicketModel',
            new_name='TicketModel',
        ),
    ]
